# -*- coding: utf-8 -*-
"""diabetes.ipynb

Problem: Recognize diabetes in pima indian population
Dataset: https://www.kaggle.com/kumargh/pimaindiansdiabetescsv
Authors: Wojciech Iracki <s13066@pjwstk.edu.pl> , Adrian Wojewoda <s16095@pjwstk.edu.pl>

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SZdQ2SBlVwvzZdsHqAgvEz3nYLnWwof5
"""

import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
from sklearn.model_selection import train_test_split

dataframe = pd.read_csv("/content/diabetes.csv")
dataframe.head()

df_label = dataframe['Outcome']
df_features = dataframe.drop('Outcome', 1)
df_features.replace('?', -99999, inplace=True)
print(df_label.head())
df_features.head()

label = []
for lab in df_label:
    if lab == 1:
        label.append([1, 0])  # class 1
    elif lab == 0:
        label.append([0, 1])  # class 0

data = np.array(df_features)
label = np.array(label)
print(data.shape,label.shape)

x_train, x_test, y_train, y_test = train_test_split(data, label, test_size=0.2, random_state=42)
x_train.shape

model = Sequential()
model.add(Dense(500, input_dim=8, activation='sigmoid'))
model.add(Dense(100, activation='sigmoid'))
model.add(Dense(2, activation='softmax'))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model.fit(x_train,y_train, epochs=1000, batch_size=70, validation_data=(x_test, y_test))

metrics = pd.DataFrame(model.history.history)

metrics.head()